In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [2]:
print(a[0])
print(a[-1])

1
5


In [3]:
print(a + 10)
print(a * 2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [4]:
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

15
3.0
5
1


In [5]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
